name: "Release Tray Icon"

on:
  push:
    branches:
    - "release/tray-icon"

env:
  PROJECT_PATH: TrayIcon/TrayIcon.csproj

jobs:
  deploy:
    name: "Deploy"
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: 'Restore packages'
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: 'Build'
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore -c Release

      - name: 'Publish'
        run: dotnet publish ${{ env.PROJECT_PATH }} --no-build -c Release --self-contained -r win-x64 -p:PublishSingleFile=true

      - name: 'Create Release'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: "Upload Release"
        uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
          pattern: TrayIcon/bin/Release/netcoreapp3.1/win-x64/publish/*.exe
